#!/bin/bash

set -e
if [[ $# -ne 4 ]]; then
  echo "Usage: clone <github org name> <github repo original name> <your github name> <github repo fork name>"
  echo "Make sure you have previously forked the project on GitHub."
  exit 1
fi

MAIN="${MAIN:-main}"

git clone git@github.com:$3/$4.git
cd $4
git remote add upstream git@github.com:$1/$2.git
git fetch upstream
git rebase upstream/$MAIN
