#!/bin/bash

set -e

MAIN="${MAIN:-main}"

base_remote=origin
if (git remote | grep --fixed-strings --line-regexp --quiet 'upstream') then
  base_remote=upstream
fi

git branch --set-upstream-to "$base_remote/$MAIN"
