#!/bin/bash

set -e

MAIN="${MAIN:-main}"

if (git remote | grep --fixed-strings --line-regexp --quiet 'upstream') then
  git fetch upstream
  git rebase upstream/$MAIN
else
  git fetch origin
  git rebase origin/$MAIN
fi
