#!/bin/bash

set -e

MAIN="${MAIN:-main}"

if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo 'This is not a git repository.'
  exit 1
fi

if [ "`git rev-parse --abbrev-ref HEAD`" == "$MAIN" ]; then
  echo 'Rename the branch first. You were about to push your $MAIN branch.'
  exit 1
fi

if [[ `git status --porcelain` ]]; then
  echo 'WARNING! Your branch has uncommitted changes, consider "commit" or "clean".'
fi

if (! git remote | grep --fixed-strings --line-regexp --quiet 'upstream') then
  echo 'Push only works when you have an upstream; consider "save" or "publish".'
  exit 1
fi

git fetch upstream
git rebase upstream/$MAIN
#git diff upstream/$MAIN
git push -f origin `git rev-parse --abbrev-ref HEAD`
