#!/bin/bash

set -e

MAIN="${MAIN:-main}"

source "$(dirname "$0")/rebase-or-abort"

if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo 'This is not a git repository.'
  exit 1
fi

if ! current_branch=$(git symbolic-ref --quiet --short HEAD); then
  echo 'This checkout is not on a branch. Check out or create a branch first.'
  exit 1
fi

if [ "$current_branch" == "$MAIN" ]; then
  echo "Rename the branch first. You were about to push your $MAIN branch."
  exit 1
fi

if [[ $(git status --porcelain) ]]; then
  echo 'WARNING! Your branch has uncommitted changes, consider "commit" or "clean".'
fi

base_remote=origin
if (git remote | grep --fixed-strings --line-regexp --quiet 'upstream') then
  base_remote=upstream
fi

git fetch "$base_remote"
rebase_or_abort "$base_remote/$MAIN"
git push -f origin "HEAD:refs/heads/$current_branch"
